### ISSUE TITLE
Syntax Menu Displays Lotsa Dots

### ISSUE THREAD

**Issue by jth0** [heyglen/network_tech#1]
![lotsa-dots](https://cloud.githubusercontent.com/assets/805906/10316892/402568b2-6c27-11e5-8fd5-beeb23ad13ab.png)

Menu display is funny, includes many dots as syntax options. Running build 3083 and current sublime-network.

**Comment by heyglen** [comment]
The main categories "Cisco ACE/IOS/ASA" are just collections of other syntax files that are separated to different files. I've renamed them to '.' so they won't be selected.

All the split out syntax files must be moved into one gigantic syntax file per device type or maybe there is someway of hiding these from this menu.

**Comment by heyglen** [comment]
This should now be fixed in the newest version.
