### ISSUE TITLE
Syntax Highlight: Authentication, Authorizing, and Accounting

### ISSUE THREAD

**Issue by michaelmcdonald** [heyglen/network_tech#10]
# Which Syntax?:
IOS

# Expected behavior and actual behavior:
Highlight. Actual, none?

# Steps to reproduce the problem:
Review config with AAA options set.

# New Feature Description:
Would like to see highlighting of AAA configuration lines and whether it's an authentication, authorization, or accounting line. Any additional syntax highlighting would be appreciated as well.

**Comment by heyglen** [comment]
Please provide examples.

**Comment by captaindoogles** [comment]
Is there a way to get the syntax colors to work here for all the commands?
Line VTY is colored but Line Console is not. I am using Cisco IOS.

[image: image.png]




[image: image.png]


username [ACCOUNT] privilege 15 secret [ACCOUNT_PASSWORD]
login block-for 30 attempts 7 within 20
!security password min-length 9
!no service password-recovery
service password-encryption
service tcp-keepalives-in
service tcp-keepalives-out
service sequence-numbers
service timestamps log datetime localtime msec year show-timezone
service timestamps debug datetime localtime msec year show-timezone
clock timezone EST -5
clock summer-time EST recurring 2 Sun Mar 02:00 1 Sun Nov 02:00
ntp server [NTP_SVR-1] prefer
ntp server [NTP SVR-2]
no ip domain-lookup
ip domain-name [DOMAIN]
ip name-server [DNS1]
ip name-server [DNS2]
ip subnet-zero
ip classless
ip igmp snooping querier
no ip http server
no ip http secure-server
no ip finger
no service finger
no logging console
no logging monitor
no ip source-route
no service pad
spanning-tree mode rapid-pvst
! VTP Disable
vtp mode off
no vtp mode
vtp mode transparent
vtp domain locIDF##
vtp password locIDF##
vtp version 2
vtp mode off
no vtp mode
!



!***************************************************
!SSH CONFIGURE
!***************************************************
!
crypto key zeroize rsa noconfirm
crypto key generate rsa modulus 2048 noconfirm


crypto key zeroize rsa
!
!
crypto key generate rsa general-keys modulus 2048
ip ssh authentication-retries 2
ip ssh source-interface vlan 400
ip ssh version 2
ip scp server enable
!
line vty 0 15
!exec-timeout 10 30
logging synchronous
!login local
exec prompt timestamp
history size 100
transport input ssh
transport output ssh
exit
!
line console 0
exec-timeout 30 30
logging synchronous
!login local
exec prompt timestamp
history size 100
exit
!
!line aux 0
!no exec
!exit
!

**Comment by heyglen** [comment]
added most of the missing commands from your example in v 2.18

**Comment by captaindoogles** [comment]
Thank you

**Comment by michaelmcdonald** [comment]
Hi!

Sorry about the delay. Are you looking for example output to try playing around with, or an example of how I would like it colored?

**Comment by captaindoogles** [comment]
Is there a way to color it?  How would you do it?

**Comment by heyglen** [comment]
`service timestamps log datetime localtime msec year show-timezone`
`service timestamps debug datetime localtime msec year show-timezone`

According to [this command reference](https://www.cisco.com/c/en/us/td/docs/ios/fundamentals/command/reference/cf_book/cf_r1.html#wp1030116) these are not valid commands

the `msec` part is only used with datetime, not localtime.

What version of IOS is it? Can you link the command reference

**Comment by heyglen** [comment]
From your example commands, the highlighting should now be in place.

The exception is the `service timestamps` commands I commented on above and anything in the pictures you attached that I am unable to see.

**Comment by heyglen** [comment]
No updates, I assume everything is ok so I am closing this issue. 

You can always open a new one.
