### ISSUE TITLE
Plugin blocks popups form other plugins

### ISSUE THREAD

**Issue by nvtkaszpir** [heyglen/network_tech#11]
This plugin conflicts with other plugins which produce popups, for example it breaks functionality of SublimeText. Disabling Network Tech plugin solves the issue.

# Which Syntax?:
any.

# Expected behavior and actual behavior:
Expected behavior: Activate only on specific file types, do not override popups.
Actual behavior: Popups from other plugins are suppressed and thus they do not show. Disabling Network Tech plugin solves the issue.

# Steps to reproduce the problem:
Install SublimeLinter, use any linter in it.
More details https://github.com/SublimeLinter/SublimeLinter/issues/1116
# New Feature Description:
N/A.

**Comment by heyglen** [comment]
Fixed in 2.12.0

Thanks for reporting.
