### ISSUE TITLE
Network / Subnet Information Not Provided

### ISSUE THREAD

**Issue by cdw-ryan** [heyglen/network_tech#14]
# Which Syntax?: Cisco IOS

# Expected behavior and actual behavior:

Mousing over or typing in an IP Address and seeing the pertinent network information appear in a pop-up as shown here: https://network-tech.readthedocs.io/en/latest/context_info.html

No information is popping up (not even a blank box).

System information: macOS Mojave 10.14.2
Sublime Text 3 ver 3.1.1 Build 3176
Network Tech package installed via Package Control 1/4/2019

# Steps to reproduce the problem:

Type line entry "ip address 10.0.0.1 255.255.255.0"

No information is displayed when moused over, typed, or highlighted. Auto-complete information is displayed while typing line as expected.

# New Feature Description:

N/A

# Example Syntax

# Link to command reference

https://network-tech.readthedocs.io/en/latest/context_info.html

**Comment by cdw-ryan** [comment]
Also after more investigation I also cannot use any of the commands in Package Control that are supposed to be invoked using "Network ..." when I start typing network nothing shows up in my available list

**Comment by theurge14** [comment]
Same here, I cannot get the subnet popups to work, and in the command palette nothing for Network Tech appears, so no searching either.

<img width="1020" alt="screen shot 2019-01-05 at 9 37 48 pm" src="https://user-images.githubusercontent.com/18601802/50731755-52ff2280-1132-11e9-935a-8feb430f40c8.png">

**Comment by heyglen** [comment]
Doh, had a missing import error in some of the python code.

Just released v2.21.1 with the fix.

**Comment by theurge14** [comment]
Update worked, thanks!
