### ISSUE TITLE
Syntax Highlight: Port-Security on Switches

### ISSUE THREAD

**Issue by tiagofilipesilva** [heyglen/network_tech#16]
# Which Syntax?:
IOS
# Expected behavior:
Syntax Highlight
# Actual behavior:
No Syntax Highlight
# New Feature Description:
Port-Security is used to restrict input to an interface via MAC addresses.
As of the current release there is no syntax highlight for this feature.
# Example Syntax
## Notation Used
{} :: optional
[] :: mandatory
| :: option separator
<mac_address> :: 48-bit MAC address with H.H.H notation
<aging_time>, <maximum_addresses>, <packets_per_sec> :: <1 .. verylargeinteger>
## Example Interface Configuration
```
interface GigabitEthernet 0/1
switchport mode access
! enables port-security, no syntax highlight from this point on, with the exception of the switchport keyword and no line
switchport port-security
! aging
switchport port-security aging [ static | time <aging_time> | type {absolute | inactivity} ]
! mac-address
switchport port-security mac-address [ <mac_address>  | sticky {<mac_address>} ]
! maximum
switchport port-security maximum { <maximum_addresses> }
! violation
switchport port-security violation [ protect | restrict | shutdown ]
! limit rate invalid-source-mac
switchport port-security limit rate invalid-source-mac [ none | <packets_per_sec> ]
end
! tabular information of all interfaces
show port-security address
! information of a specific interface
show port-security {address} interface interface_id
```
# Link to command reference
[Catalyst 4500 Series Switch Cisco IOS Software Configuration Guide](https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst4500/12-2/25ew/configuration/guide/conf/port_sec.html)

**Comment by heyglen** [comment]
Hi,

I've added support for this in version [2.23.0](https://github.com/heyglen/network_tech/releases/tag/2.23.0)

Thanks for reporting :smiley: 

/Glen

**Comment by tiagofilipesilva** [comment]
Hi @heyglen !
limit rate invalid-source-mac was left out of the definitions. Would it be possible to add it later on?
Thank you!
