### ISSUE TITLE
not finding in Package Installer for Sublime Text 3

### ISSUE THREAD

**Issue by elijahblake81** [heyglen/network_tech#17]
# Which Syntax?:

# Expected behavior and actual behavior:

# Steps to reproduce the problem:

# New Feature Description:

# Example Syntax

# Link to command reference
![image](https://user-images.githubusercontent.com/6844968/54685600-32b1f380-4ae5-11e9-9603-5cc618f127e1.png)

**Comment by tiagofilipesilva** [comment]
Hi @elijahblake81!
In order to use this package you need to reproduce the steps from the [documentation](https://network-tech.readthedocs.io/en/latest/).

**Comment by oyvellef** [comment]
Same issue here, after upgrading to Sublime 3200. Sublime 3200 complain about not being able to open the package on startup after upgrade.

**Comment by heyglen** [comment]
Hi,

Which OS are you seeing the problem on?

Can I see a screen shot of the error? 

Are there any errors in the console?: View -> Show Console

The screen shot included on the original issue shows network tech is not available, is this the list of packages under "Package Control: Install Package"? Is it in the "Package Control: Remove Package" list?

**Comment by elijahblake81** [comment]
Yes,  mine is in the Package Control: Remove Package, wow!  So sorry, someone else helped me get started with sublime text 3 a few days ago and I guess they had already installed it.  Sorry about the confusion.  Thank you for the help!

**Comment by heyglen** [comment]
Your welcome 🙂
