### ISSUE TITLE
Password Decode not parsing

### ISSUE THREAD

**Issue by merriry** [heyglen/network_tech#20]
# Which Syntax?:
mode 7 Password Decode
# Expected behavior and actual behavior:
A line like:
username <redacted> privilege 15 password 7 <redacted>
Should be detected by the password decode algorithm and decoded.
Currently it is not.

**Comment by heyglen** [comment]
Hi Merriry,

If we are talking about Cisco IOS syntax. Here is my (working) test case:

![image](https://user-images.githubusercontent.com/6285388/56786454-527dbb00-67f9-11e9-9046-61c0680ef395.png)

Which syntax are you talking about (IOS, IOS-XR, NXOS) and what is the _exact_ command that will not decode? You should of course *** out the password.

**Comment by heyglen** [comment]
Hi Merriry,

Fixed in 2.27.0.

Thanks for reporting :)

/Glen
