### ISSUE TITLE
Recent Commit to messages.json results in parsing error

### ISSUE THREAD

**Issue by danieldjewell** [heyglen/network_tech#23]
Hello! 

I just updated the package to the latest version from Package Control -- I got an error parsing messages.json in the console. The problem appears to be an extraneous comma at the end of the line: 

https://github.com/heyglen/network_tech/blob/936180433e68a6942f7aebd945282631e5085906/messages.json#L30

**Comment by heyglen** [comment]
Fixed! Thank you 🙂

**Comment by danieldjewell** [comment]
Happy to help! :) Thank you!
