### ISSUE TITLE
Voice Additions

### ISSUE THREAD

**Issue by danieldjewell** [heyglen/network_tech#27]
So, I finally had some time and got around to those voice additions in #7 ... sorry about the delay. :grin:

I wanted to get some feedback before I did a PR -- I have not yet finished the changes to the syntax_test file (which would be part of a PR) 

https://github.com/danieldjewell/network_tech/commit/778526fb7c33ffb02fc69bc381a2f94d29bf0df5

**Comment by heyglen** [comment]
Hi Daniel,

I am using the test files in [the tests directory](https://github.com/heyglen/network_tech/tree/master/tests) to visually confirm that changes do not screw up existing syntax highlighting.

Could you write sample configurations for your syntax into the [Cisco IOS test](https://github.com/heyglen/network_tech/blob/master/tests/syntax_test_cisco_ios.cisco-ios) as a part of your merge?

/Glen

**Comment by danieldjewell** [comment]
Yes, absolutely -- I was testing against some real configs and didn't have a chance to rewrite/sanitize for the test file, but I will before submitting a PR. :)

**Comment by heyglen** [comment]
Issue #7 is closed
