### ISSUE TITLE
"interface range Gi1/0/1-20" in highlighted differently than "interface Gi1/0/1"

### ISSUE THREAD

**Issue by pako-pl** [heyglen/network_tech#3]
In both command, the interface names should be highligted in the same way. Only the first version of the command seems to be recognized:

```
interface Gi1/0/1
exit

interface range Gi1/0/1-20
exit
```

**Comment by heyglen** [comment]
Fixed in 82d57b35bb9fdf664a6bc52501946104a8c0caf1

**Comment by pako-pl** [comment]
Thank you, I can confirm that "interface range" is highlighted correctly now.
