### ISSUE TITLE
IPSLA 

### ISSUE THREAD

**Issue by mikk674** [heyglen/network_tech#30]
Would be interested in contributing, but i have no idea where to start. If any one wants to be give me some pointers that would be awesome.
If the below could be done that would be fantastic. Work regularly with upwards of 20 of these per router and having them highlighted would be very handy. 

# Which Syntax?:
IOS Classic

# Expected behavior and actual behavior:
Expected to be highlighed 
Actually not being highlighted

# Steps to reproduce the problem:
Type in the commands in the example
# New Feature Description:
Highlighted in the same fashion as the 

# Example Syntax
ip sla 1
 icmp-echo 10.102.64.114 source-interface Tunnel710
 tos 184
 vrf agr_usi_vpn
 threshold 2000
 frequency 5
ip sla schedule 1 life forever start-time now

# Link to command reference

**Comment by mikk674** [comment]
Oh forgot a link

https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipsla/configuration/15-mt/sla-15-mt-book.html

**Comment by heyglen** [comment]
There is some supported IP SLA commands in the [IOS syntax](https://github.com/heyglen/network_tech/blob/master/tests/syntax_test_cisco_ios.cisco-ios#L969-L988):

```
ip sla 1
  icmp-echo 10.0.0.1 source-ip 192.100.0.0
  icmp-echo 10.0.0.1 source-ip 1::1
  icmp-echo 10.0.0.1 source-interface Tunnel123
  icmp-echo 0:0:0:1::1 source-interface Tunnel123
  icmp-echo host.example.com source-interface Tunnel123
  tag ASCII_TAG
  tos 184
  vrf RED
  threshold 2000
  frequency 5

ip sla schedule 1 life 1
ip sla schedule 1 life forever start-time now
ip sla schedule 1 start-time now
ip sla schedule 1 start-time pending
ip sla schedule 1 start-time after 01:02
ip sla schedule 1 start-time after 01:02:03
ip sla schedule 1 ageout 20
ip sla schedule 1 recurring
```

Is this sufficient? 

The link you provided contains 25+ chapters, can you instead link the commands (preferably in the command reference) you are using?

**Comment by mikk674** [comment]
Hi heyglen

Thank you for working on this. My apologies for not being more specific. Looks like you have gotten the majority of what i was looking for non the less. 

3 additional things from seeing it implemented;
timeout - not highlighted
highlighting the tag <name> appears to not highlight the full length of the name.
udp jitter
![image](https://user-images.githubusercontent.com/54020917/76430856-b88b1680-63a8-11ea-8ba6-6352944f9b21.png)


udp-jitter detailed - also includes timeout
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipsla/configuration/15-mt/sla-15-mt-book/sla_udp_jitter.html

Thank you very much in advance 

mikk674

**Comment by heyglen** [comment]
Added UDP Jitter & Timeout in 2.37.0.

[This Command Reference](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipsla/command/sla-cr-book/sla_s2.html#wp3793668867) claims the tag name should be 0-16 characters, can you double check?
