### ISSUE TITLE
Network Tech issue: I can no longer get subnet details moving the mouse over an ip address

### ISSUE THREAD

**Issue by xavieranye** [heyglen/network_tech#35]

**Comment by heyglen** [comment]
Hi did you accidentally toggle it off?:

[docs](https://network-tech.readthedocs.io/en/latest/context_info.html)

**Comment by heyglen** [comment]
I am unable to reproduce this. 

Can you also try to uninstall & reinstall Network Tech?

Are you using Windows, Mac or Linux?

Does any error appear in the console? (View → Show Console)

**Comment by xavieranye** [comment]
Hi  Glen,
Thank  you so very much  for your assistance..  not sure how that  happened
; but your solution  was a gem...
cannot thank you enough.
Just for my sanity, in case this relevant functionally get deactivated by
mistake  , I  just have to repeat the steps you mentioned  or  is there a
way  to have this "Network Tech :Toggle network info  Popup on  Hover" as
tab ?

Cheers

**Comment by heyglen** [comment]
Hi xavieranye,

You can access the "Network Tech :Toggle Network Info Popup on  Hover" via the command pallet:

![image](https://user-images.githubusercontent.com/6285388/113825776-adf4a980-9781-11eb-862a-6accb249a421.png)
