### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by bill2222** [heyglen/network_tech#37]
Hello,

Network Tech package is great but I would like to customize the color for certain keywords. Example, for "VLAN" I would like to choose a different color than what's in the package. Is this possible? I tried looking through the package files but haven't found the file that needs to be edited yet.

**Comment by heyglen** [comment]
Hi Bil,

Never did this before, but here is what I found:

Use something like [ScopeAlways](https://packagecontrol.io/packages/ScopeAlways) to identify the `scope` of the keyword you want to color. 

Create a `.sublime-color-scheme` file in your `Packages/User/` directory with the style definitions you want to apply to each scope. See [Sublime Text Color Schemes Example](https://www.sublimetext.com/docs/3/color_schemes.html#example) 

I am not sure how this can be limited to a single syntax type (Ex: "Cisco IOS"), perhaps through naming: `Cisco IOS.sublime-color-scheme`?
