### ISSUE TITLE
Missing/Incomplete Highlighting for IOS XR Hundred/FortyGig.

### ISSUE THREAD

**Issue by nightf0x** [heyglen/network_tech#38]
"{ Incomplete } Syntax Highlighting"

IOS-XR

Example

```
interface HundredGigE0/0/0/0
```

## Expected behavior and actual behavior
Expect the interface to be color coded like other interfaces. Interface is not highlighted.

## Steps to reproduce the problem
Load any IOS XR config with hundredgig interfaces.

What is the problem?
Hundredgig interfaces are not highlighted and there for the following config lines associated with the interface are not highlighted either. 

How might it be solved?
Please add hundredgig interface support.

P.S FortyGig has incomplete highlighting as well but at least it has some which allows for the remainder of its associated config to be highlighted.
interface FortyGigE0/0/0/10
Highlighting stops at Fo.

![Screen Shot 2021-05-05 at 4 30 17 PM](https://user-images.githubusercontent.com/1833817/117205189-456c0d00-adbf-11eb-9fa6-363004b1d4b2.png)

**Comment by heyglen** [comment]
Added in v2.51.1
