### ISSUE TITLE
Can no longer load 

### ISSUE THREAD

**Issue by Bluffkin** [heyglen/network_tech#4]
Getting error 

Error loading syntax file "Packages/sublime-network/cisco/asa/syntax/CiscoASA.tmLanguage": Unable to open Packages/sublime-network/cisco/asa/syntax/CiscoASA.tmLanguage

Happened when I upgraded to Sublime text 3 build 3114 from 3103

**Comment by heyglen** [comment]
I upgraded the syntax files to the new .sublime-syntax format replacing these old .tmLanguage files.

Set the syntax on the file again and it should be fine.

**Comment by Bluffkin** [comment]
You've also removed the syntax folder. Sorry I am a bit of a sublime noob. So I am going to create the syntax folder, rename the file and place it there? I'll give it a go now and let you know. 

Steve

**Comment by heyglen** [comment]
Did you follow the suggestion I made?

**Comment by Bluffkin** [comment]
I followed the suggestions I interpreted you made, and what I said "So I am going to create the syntax folder, rename the file and place it there? I'll give it a go now and let you know." Didn't fix the issue.

**Comment by heyglen** [comment]
Reinstall the package so you undo the direct edits you made to the package. Then in the bottom right corner you can select the syntax:

![image](https://cloud.githubusercontent.com/assets/6285388/15477683/47f9c1d8-2116-11e6-9d59-a6423cd74684.png)

Set it again so it loads the correct syntax file.

Also, be aware that the [syntax rules have changed to strictly follow which configuration mode you are in](../blob/master/docs/configuration_modes.md)

**Comment by Bluffkin** [comment]
Ah it was the configuration mode. Entering the correct config mode brings it all up. 

As a side question, is there a way to turn that off? Or is it hard coded?

**Comment by heyglen** [comment]
You cannot turn it off. It is a design choice.

Enforcing the proper configuration modes allows completions and syntax to be specific.

It is also less buggy, in the previous versions moving in and out of configuration modes was tricky since there were no clear end markers to match.
