### ISSUE TITLE
Unable to install Network Tech package in Sublime 3 or 4

### ISSUE THREAD

**Issue by culloa1** [heyglen/network_tech#40]
Im trying to install the Network tech package but after installing it im not seeing it under the installed packages.

**Comment by mboback-spg** [comment]
Running into same issue here also - any ideas?

**Comment by heyglen** [comment]
I am sometimes seeing problem in ST4, but restarting it fixes it.

Can you confirm a restart works?

**Comment by mboback-spg** [comment]
Restarted my system and this did seem to in fact fix it. Restarting Sublime Text by itself did not resolve.

Thanks!
