### ISSUE TITLE
Contribute to repo

### ISSUE THREAD

**Issue by sschwetz** [heyglen/network_tech#41]
Hi Glen,
I have an apple keybinding that I would like to contribute to the repo. I have also forked your project and will be creating snippets and syntax for HPE Comware, Aruba, and Fortinet Products. If you are ok, I would look forward to submitting pull requests once completed to compliment your work so far

**Comment by heyglen** [comment]
That would be great, please do.

**Comment by sschwetz** [comment]
Not a problem, Do you have documentation on how you put this together?

**Comment by michaelmcdonald** [comment]
2nd the desire to contribute! If you put together some basic information on how to add additional syntax to Network_Tech I would be more than glad to work on adding Juniper / Junos to it!

**Comment by heyglen** [comment]
I have created a [contribution guide](https://network-tech.readthedocs.io/en/latest/src/contribute/) as a start.

I am unsure what information you need. I will add or adjust it with your feedback.
