### ISSUE TITLE
Provide Manual Installation Instructions

### ISSUE THREAD

**Issue by techfixpros** [heyglen/network_tech#42]
I have 2 work-issued laptops (on-network and off-network). One uses a permanent Cisco VPN (on-network) and the other uses standard windows networking (off-network). I can of course install anything at anytime on the off-network laptop, but the on-network uses the VPN and blocks access to GitHub, so I cannot install packages using package manager. I am in IT, just not the cyber dept., and have "full" local admin rights on both laptops.

**Comment by heyglen** [comment]
Hi,

Try this:

Git clone this repo. Take the cloned folder and copy it into the directory that pops up when you go to Preferences → Browse Packages... in ST
