### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by edurguti** [heyglen/network_tech#43]
Hi, this is not an issue, love the package, I can't seem to find where you're setting the colors (if you are), I'd love to port them to SEcureCRT and iterm2 so I have a consistent experience.

**Comment by heyglen** [comment]
Woah, I would like to see how you do that.

I am not setting any colors, I'm using built in scopes.

I used the [Syntax Highlighting Scopes Showroom](https://packagecontrol.io/packages/Syntax%20Highlighting%20Scopes%20Showroom) to dump all the scopes and check their colors:

![image](https://user-images.githubusercontent.com/6285388/145959355-287eaadb-973b-4f2f-a12b-43ed856bcf7d.png)

Then picked scope names that look somewhat correct from the list:
![image](https://user-images.githubusercontent.com/6285388/145959424-67c0c44f-771d-4c2f-a552-8e5ba85c643c.png)

...the only way I can think of grabbing the colors is using something like [Paint.net](https://www.getpaint.net/download.html)'s color picker tool to grab the color codes:

![image](https://user-images.githubusercontent.com/6285388/145959949-e5c3735e-44d8-4d01-9d35-e835a448412e.png)

...a bit tedious.

**Comment by edurguti** [comment]
Yeah, I ended up doing the color picker, here's iterm2 on the left and sublime on the right:

Still work in progress, but it's being done via iterm2 "triggers" with a bunch of regex mess :)
![image](https://user-images.githubusercontent.com/19334167/146229196-e01cfc96-ae99-4162-89c4-fc05fdbd0a62.png)


https://iterm2.com/documentation-triggers.html

**Comment by heyglen** [comment]
nice... this project is nothing without the regex mess :)

Your iterm setup looks great. I'm a Windows user so I'll cross my fingers that something similar comes to Windows Terminal.
