### ISSUE TITLE
other vendors

### ISSUE THREAD

**Issue by SebUll** [heyglen/network_tech#44]
Hi,

I know it is not directly related to the topic but would it be possible to implement the whole thing for other manufacturers? I would be very happy about a positive answer.

Many greetings

**Comment by heyglen** [comment]
Hi,

It is possible, but can be lot of work. For example, [Cisco IOS](https://github.com/heyglen/network_tech/blob/master/cisco-ios.sublime-syntax) is 5.5k lines. 

The syntax I created were done over many years by hand. I don't have any quick solution to easily implement new syntax.

If you are up to it you can make your own and contribute it.
