### ISSUE TITLE
New / Incomplete IOS-XR Syntax Highlighting

### ISSUE THREAD

**Issue by hardrockhodl** [heyglen/network_tech#45]
### IOS-XR Example 1
- add TwentyFiveGigE interface type 
```
interface TwentyFiveGigE0/0/0/40
```
- to cisco-ios-xr.sublime-syntax:
```
interface_names: |
    (?:TwentyFiveGigE)|
    (?:TwentyFiveGigEthernet)|
    (?:Twe)|
```

### IOS-XR Example 2 (ASR 9K) - L2VPN and EVPN
Sorry I cant figure out how you setup this in your file.
You have to do your magic.
```
l2vpn
 bridge group 6005
  bridge-domain 6005
   interface Bundle-Ether2.1
    evi 6005
!
interface BVI34
 host-routing
 vrf 30
 ipv4 address 10.0.0.5 255.0.0.0
 arp learning local
 local-proxy-arp
 mac-address 1.1.1
!
!
evpn
 interface Bundle-Ether1
   ethernet-segment
   identifier type 0 40.00.00.00.00.00.00.00.01
   load-balancing-mode single-active
   bgp route-target 4000.0000.0001
 !
 evi 6005
  bgp
   rd 200:50
   route-target import 100:6005
   route-target export 100:6005
!
!
interface bundle-ether2.1 l2transport
  no shutdown
  encapsulation dot1q 1
  rewrite ingress tag pop 1 symmetric
!
```
## Link to Command Reference
https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-5/lxvpn/configuration/guide/b-l2vpn-cg-asr9000-75x/configure-evpn-irb.html#task_7CAD3A1F2C9C4A939EAFE97BDA35B8BA

**Comment by heyglen** [comment]
Released these commands:

```
l2vpn
  bridge group NAME
    bridge-domain NAME
      interface Bundle-Ether2.1
        evi 6005
        evi 65534
        evi 1
        evi 65535  # Should Fail
        evi 0  # Should Fail
      exit
    exit
  exit

interface BVI34
 host-routing
 vrf 30
 ipv4 address 10.0.0.5 255.0.0.0
 arp learning local
 arp learning disable
 local-proxy-arp
 mac-address 0123.4567.89ab
!
```

The "exits" were needed in the l2vpn blocks because the "config t" interface block would otherwise be confused with the "l2vpn →  bridge group →  bridge domain → interface" block

**Comment by heyglen** [comment]
All commands should be added in 2.56.0

**Comment by heyglen** [comment]
L2VPN:
![image](https://github.com/heyglen/network_tech/assets/6285388/0eae65b8-d0d4-49d8-a461-ca586daaef5a)

Missing interface commands
![image](https://github.com/heyglen/network_tech/assets/6285388/18c9606e-7c99-46c9-9b79-b97d211d07dc)

EVPN
![image](https://github.com/heyglen/network_tech/assets/6285388/d0ed6836-2c40-4762-91d4-786d48f92417)

Interface Rewrite
![image](https://github.com/heyglen/network_tech/assets/6285388/03174dda-0ca1-4907-9a7a-0ff88542f3e9)

Command autocompletions
![image](https://github.com/heyglen/network_tech/assets/6285388/c053e5d8-56e6-45de-bf7d-8f844a6855b5)
