### ISSUE TITLE
In a ip access-list configuration there is a highlighting problem with the argument "neq"

### ISSUE THREAD

**Issue by elkero** [heyglen/network_tech#6]
Hello, 
When we write an udp sequence in an access-list, the argument used to match a specific port "eq" is highlighted normally but the argument "neq" seems to be unrecognized and the entire line become unlighted

You can see it on this screen capture
![image](https://user-images.githubusercontent.com/33523188/32616645-1d6913f8-c573-11e7-8416-4c2329890e71.png)

It is possible to fix this ? 
Thanks a lot
Léo.

**Comment by heyglen** [comment]
thanks for reporting :)
