### ISSUE TITLE
IOS Syntax Additions - Voice & Others

### ISSUE THREAD

**Issue by danieldjewell** [heyglen/network_tech#7]
# Which Syntax?:
IOS
# Expected behavior and actual behavior:
Highlighting. Actual, none?
# Steps to reproduce the problem:
config directives for CME like dial-peer ephone telephony-service are absent
# New Feature Description:
I forked a copy, I'm going to play around with some of the options, I'd be honored if you'd consider including them. Might take me a little while.

**Comment by heyglen** [comment]
Sure, some help and voice config expertise would be great.

If you have not already seen it, take a quick look at the [contributing policy](https://github.com/heyglen/network_tech/blob/master/CONTRIBUTING.md).

**Comment by heyglen** [comment]
Hi,

Can you provide the commands you want highlighted?

**Comment by heyglen** [comment]
No updates on this in a while, I am closing it.

If you want something added, open another issue with specific examples.
