### ISSUE TITLE
Syntax Highlight: Access Control Lists

### ISSUE THREAD

**Issue by michaelmcdonald** [heyglen/network_tech#8]
# Which Syntax?:
IOS

# Expected behavior and actual behavior:
Highlight. Actual, none?

# Steps to reproduce the problem:
Review configuration containing ACLs.

# New Feature Description:
Would love to see syntax highlighting for Access Control lists. Something that highlights that it _is_ an ACL, if it's permit / deny, the IPs / object-groups contained, etc...

**Comment by heyglen** [comment]
Please provide examples.

This is what is supported [from the test config](https://github.com/heyglen/network_tech/blob/master/tests/syntax_test_cisco_ios.cisco-ios):
![image](https://user-images.githubusercontent.com/6285388/40613809-5a6e93a4-6280-11e8-8439-0dac740d792e.png)

**Comment by michaelmcdonald** [comment]
Hi!

Sorry about the delay. Are you looking for example output to try playing around with, or an example of how I would like it colored?

**Comment by heyglen** [comment]
I attached a screen shot with the ACL syntax highlighting. What are the commands that do not work?

I only need the commands, I will figure out the coloring.

**Comment by heyglen** [comment]
Hi Michael,

[Release 2.22.0](
https://github.com/heyglen/network_tech/releases/tag/2.22.0) has some support for IOS object groups. The documentation I found for the ACL syntax is not very good so I would appreciate some feedback and or syntax examples.

**Comment by heyglen** [comment]
No updates, closing the issue.
