### ISSUE TITLE
Syntax Highlight: Simple Network Management Protocol

### ISSUE THREAD

**Issue by michaelmcdonald** [heyglen/network_tech#9]
# Which Syntax?:
IOS

# Expected behavior and actual behavior:
Highlight. Actual, none?

# Steps to reproduce the problem:
Review config containing SNMP configuration.

# New Feature Description:
Would like to see SNMP configuration lines highlighted. Highlighting that it _is_ an SNMP line, if changes were added / removed,

**Comment by heyglen** [comment]
Examples please

**Comment by michaelmcdonald** [comment]
Hi!

Sorry about the delay. Are you looking for example output to try playing around with, or an example of how I would like it colored?

**Comment by heyglen** [comment]
Ah yes, I should be clearer :)

The example commands are enough... links to the command reference is even better.

**Comment by merriry** [comment]
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/snmp/command/nm-snmp-cr-book/nm-snmp-cr-s5.html

there is the SNMP command reference.

**Comment by heyglen** [comment]
Done.
